#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MODELS_DIR="/models"
CONFIG_FILE="${SCRIPT_DIR}/selected-models.yaml"
ENGINE="${1:-}"

log_info() { echo "[INFO] $*"; }
log_warn() { echo "[WARN] $*"; }
log_error() { echo "[ERROR] $*"; }

check_prerequisites() {
    if ! command -v docker >/dev/null 2>&1; then
        log_error "Docker is not installed. Please install Docker first."
        log_error "Ubuntu: curl -fsSL https://get.docker.com | sh"
        exit 1
    fi

    if ! docker info >/dev/null 2>&1; then
        log_error "Docker daemon is not running or you lack permissions."
        log_error "Try: sudo systemctl start docker"
        log_error "Or add your user to the docker group: sudo usermod -aG docker \$USER"
        exit 1
    fi

    if ! docker info 2>/dev/null | grep -q "nvidia"; then
        log_warn "NVIDIA Container Toolkit may not be configured."
        log_warn "If GPU containers fail, install it:"
        log_warn "  https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html"
    fi

    if ! command -v python3 >/dev/null 2>&1; then
        log_error "python3 is required but not installed."
        exit 1
    fi

    if ! command -v uv >/dev/null 2>&1; then
        log_warn "uv not found. Installing uv..."
        curl -LsSf https://astral.sh/uv/install.sh | sh || {
            log_error "Failed to install uv. Please install it manually:"
            log_error "  curl -LsSf https://astral.sh/uv/install.sh | sh"
            exit 1
        }
        export PATH="$HOME/.local/bin:$PATH"
        log_info "uv installed successfully"
    fi
}

download_models() {
    log_info "Checking model availability..."
    if [ ! -f "${CONFIG_FILE}" ]; then
        log_error "selected-models.yaml not found at ${CONFIG_FILE}"
        exit 1
    fi

    if ! command -v hf >/dev/null 2>&1; then
        log_info "Installing huggingface-hub via uv..."
        uv tool install huggingface-hub[cli]
    fi

    sudo mkdir -p "${MODELS_DIR}"
    sudo chmod 777 "${MODELS_DIR}" || true

    if [ -d "$HOME/.cache/huggingface" ]; then
        sudo chown -R "$(id -u):$(id -g)" "$HOME/.cache/huggingface" 2>/dev/null || true
    fi

    export HF_HOME="${HF_HOME:-$HOME/.cache/huggingface}"
    python3 "${SCRIPT_DIR}/scripts/download_models.py" \
        --config "${CONFIG_FILE}" \
        --model "EXAONE-3.5-32B-Instruct" \
        ${HF_TOKEN:+--token "${HF_TOKEN}"} \
        || {
            log_error "Model download/check failed"
            exit 1
        }
}

select_engine() {
    if [ -n "${ENGINE}" ]; then
        case "${ENGINE}" in
            vllm|sglang|tensorrtllm)
                log_info "Using engine: ${ENGINE}"
                ;;
            *)
                log_error "Unknown engine: ${ENGINE}"
                log_error "Supported: vllm, sglang, tensorrtllm"
                exit 1
                ;;
        esac
        return 0
    fi

    echo ""
    echo "=========================================="
    echo "  Select Inference Engine"
    echo "=========================================="
    echo "1) vLLM        - Recommended for EXAONE"
    echo "2) SGLang      - Experimental for EXAONE"
    echo "3) TensorRT-LLM - AutoDeploy backend"
    echo ""
    read -rp "Enter choice [1-3]: " choice

    case "${choice}" in
        1) ENGINE="vllm" ;;
        2) ENGINE="sglang" ;;
        3) ENGINE="tensorrtllm" ;;
        *)
            log_error "Invalid choice"
            exit 1
            ;;
    esac

    log_info "Selected engine: ${ENGINE}"
}

setup_env_file() {
    local env_file="${SCRIPT_DIR}/.env"

    if [ ! -f "${env_file}" ]; then
        log_info "Creating .env file..."
        cat > "${env_file}" <<EOF
# InferencePack Environment Configuration
# Generated by run.sh on $(date)

# HuggingFace Token (required for gated models)
HF_TOKEN=${HF_TOKEN:-}

# vLLM API Key (optional - enables API authentication)
VLLM_API_KEY=${VLLM_API_KEY:-}

# LangFuse Security Keys
NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-inferencepack-secret-$(openssl rand -hex 16)}
SALT=${SALT:-inferencepack-salt-$(openssl rand -hex 16)}
ENCRYPTION_KEY=${ENCRYPTION_KEY:-$(openssl rand -hex 32)}
REDIS_AUTH=${REDIS_AUTH:-$(openssl rand -hex 16)}

# LangFuse Initial User (optional - auto-created on first run)
LANGFUSE_INIT_USER_EMAIL=${LANGFUSE_INIT_USER_EMAIL:-netai@smartx.kr}
LANGFUSE_INIT_USER_NAME=${LANGFUSE_INIT_USER_NAME:-admin}
LANGFUSE_INIT_USER_PASSWORD=${LANGFUSE_INIT_USER_PASSWORD:-netai123}

# LangFuse API Keys (get from LangFuse UI after first startup)
LANGFUSE_PUBLIC_KEY=${LANGFUSE_PUBLIC_KEY:-}
LANGFUSE_SECRET_KEY=${LANGFUSE_SECRET_KEY:-}

# OpenTelemetry endpoint for native engine tracing to LangFuse
OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://langfuse-web:3000/api/public/otel/v1/traces
OTEL_EXPORTER_OTLP_TRACES_PROTOCOL=http/protobuf
OTEL_SERVICE_NAME=inferencepack-engine
EOF
        log_info ".env file created at ${env_file}"
        log_info "Please review and update HF_TOKEN and LangFuse API keys if needed"
    fi
}

start_langfuse() {
    log_info "Starting LangFuse services..."
    cd "${SCRIPT_DIR}"
    docker compose -f docker-compose.langfuse.yml up -d
}

start_engine() {
    log_info "Starting ${ENGINE} inference engine..."
    cd "${SCRIPT_DIR}"

    local compose_file="docker-compose.${ENGINE}.yml"
    if [ ! -f "${compose_file}" ]; then
        log_error "Compose file not found: ${compose_file}"
        exit 1
    fi

    docker compose -f "${compose_file}" up -d

    log_info ""
    log_info "=========================================="
    log_info "  InferencePack is starting up"
    log_info "=========================================="
    log_info "LangFuse UI:     http://localhost:3000"
    log_info "API Endpoint:    http://localhost:8000/v1"
    log_info "Engine:          ${ENGINE}"
    log_info ""
    log_info "To monitor logs: docker compose -f ${compose_file} logs -f"
    log_info "To stop:         docker compose -f ${compose_file} down"
    log_info ""
    log_info "First-time LangFuse setup:"
    log_info "  1. Visit http://localhost:3000"
    log_info "  2. Sign in with the credentials from your .env file"
    log_info "  3. Create a project and copy the API keys"
    log_info "  4. Add LANGFUSE_PUBLIC_KEY and LANGFUSE_SECRET_KEY to .env"
    log_info "  5. Restart the engine: docker compose -f ${compose_file} restart"
    log_info ""
}

wait_for_health() {
    log_info "Waiting for services to be healthy..."
    sleep 5

    local max_attempts=60
    local attempt=0

    while [ $attempt -lt $max_attempts ]; do
        if docker compose ps 2>/dev/null | grep -q "healthy"; then
            log_info "Services are healthy"
            return 0
        fi
        attempt=$((attempt + 1))
        sleep 5
    done

    log_warn "Some services may still be starting. Check logs with:"
    log_warn "  docker compose -f docker-compose.${ENGINE}.yml logs -f"
}

main() {
    log_info "InferencePack Setup Starting..."
    log_info "Script directory: ${SCRIPT_DIR}"

    check_prerequisites
    select_engine
    download_models
    setup_env_file
    start_langfuse
    start_engine
    wait_for_health

    log_info "InferencePack setup complete!"
}

main "$@"
