#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MODELS_DIR="/models"
CONFIG_FILE="${SCRIPT_DIR}/selected-models.yaml"
ENGINE="${1:-}"

log_info() { echo "[INFO] $*"; }
log_warn() { echo "[WARN] $*"; }
log_error() { echo "[ERROR] $*"; }

install_docker() {
    if command -v docker >/dev/null 2>&1; then
        log_info "Docker already installed: $(docker --version)"
        return 0
    fi

    log_info "Installing Docker..."
    curl -fsSL https://get.docker.com | sh
    sudo usermod -aG docker "${USER}" || true
    sudo systemctl enable docker
    sudo systemctl start docker
    log_info "Docker installed successfully"
}

install_nvidia_container_toolkit() {
    if docker info 2>/dev/null | grep -q "nvidia"; then
        log_info "NVIDIA Container Toolkit already configured"
        return 0
    fi

    log_info "Installing NVIDIA Container Toolkit..."
    if ! command -v nvidia-smi >/dev/null 2>&1; then
        log_warn "nvidia-smi not found. Please ensure NVIDIA drivers are installed."
        log_warn "Continuing anyway..."
    fi

    curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg
    curl -s -L https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list | \
        sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | \
        sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list

    sudo apt-get update
    sudo apt-get install -y nvidia-container-toolkit
    sudo nvidia-ctk runtime configure --runtime=docker
    sudo systemctl restart docker
    log_info "NVIDIA Container Toolkit installed"
}

install_python_deps() {
    if python3 -c "import huggingface_hub, yaml" 2>/dev/null; then
        log_info "Python dependencies already installed"
        return 0
    fi

    log_info "Installing Python dependencies..."
    sudo apt-get update
    sudo apt-get install -y python3-pip python3-yaml
    pip3 install --user huggingface_hub PyYAML
    log_info "Python dependencies installed"
}

download_models() {
    log_info "Checking model availability..."
    if [ ! -f "${CONFIG_FILE}" ]; then
        log_error "selected-models.yaml not found at ${CONFIG_FILE}"
        exit 1
    fi

    sudo mkdir -p "${MODELS_DIR}"

    python3 "${SCRIPT_DIR}/scripts/download_models.py" \
        --config "${CONFIG_FILE}" \
        ${HF_TOKEN:+--token "${HF_TOKEN}"} \
        || {
            log_error "Model download/check failed"
            exit 1
        }
}

select_engine() {
    if [ -n "${ENGINE}" ]; then
        case "${ENGINE}" in
            vllm|sglang|tensorrtllm)
                log_info "Using engine: ${ENGINE}"
                ;;
            *)
                log_error "Unknown engine: ${ENGINE}"
                log_error "Supported: vllm, sglang, tensorrtllm"
                exit 1
                ;;
        esac
        return 0
    fi

    echo ""
    echo "=========================================="
    echo "  Select Inference Engine"
    echo "=========================================="
    echo "1) vLLM        - Recommended for EXAONE"
    echo "2) SGLang      - Experimental for EXAONE"
    echo "3) TensorRT-LLM - AutoDeploy backend"
    echo ""
    read -rp "Enter choice [1-3]: " choice

    case "${choice}" in
        1) ENGINE="vllm" ;;
        2) ENGINE="sglang" ;;
        3) ENGINE="tensorrtllm" ;;
        *)
            log_error "Invalid choice"
            exit 1
            ;;
    esac

    log_info "Selected engine: ${ENGINE}"
}

setup_backend_url() {
    case "${ENGINE}" in
        vllm)
            BACKEND_URL="http://vllm:8000"
            ;;
        sglang)
            BACKEND_URL="http://sglang:30000"
            ;;
        tensorrtllm)
            BACKEND_URL="http://tensorrtllm:8000"
            ;;
    esac

    export BACKEND_URL
    log_info "Backend URL set to: ${BACKEND_URL}"
}

setup_env_file() {
    local env_file="${SCRIPT_DIR}/.env"

    if [ ! -f "${env_file}" ]; then
        log_info "Creating .env file..."
        cat > "${env_file}" <<EOF
# InferencePack Environment Configuration
# Generated by run.sh on $(date)

# HuggingFace Token (required for gated models)
HF_TOKEN=${HF_TOKEN:-}

# vLLM API Key (optional, for API authentication)
VLLM_API_KEY=${VLLM_API_KEY:-}

# LangFuse Configuration
NEXTAUTH_SECRET=inferencepack-secret-$(openssl rand -hex 16)
SALT=inferencepack-salt-$(openssl rand -hex 16)
ENCRYPTION_KEY=$(openssl rand -hex 32)
REDIS_AUTH=$(openssl rand -hex 16)

# LangFuse Initial User (optional - set to auto-create on first run)
LANGFUSE_INIT_USER_EMAIL=netai@smartx.kr
LANGFUSE_INIT_USER_NAME=admin
LANGFUSE_INIT_USER_PASSWORD=netai123

# LangFuse API Keys (generate these from LangFuse UI after first startup)
LANGFUSE_PUBLIC_KEY=
LANGFUSE_SECRET_KEY=

# OpenTelemetry Endpoint (optional - set to send traces to LangFuse)
# OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://langfuse-web:3000/api/public/otel/v1/traces

# Engine selection
BACKEND_URL=${BACKEND_URL:-http://vllm:8000}
ENABLE_LANGFUSE=true
EOF
        log_info ".env file created at ${env_file}"
        log_info "Please review and update HF_TOKEN and LangFuse API keys"
    else
        sed -i "s|^BACKEND_URL=.*|BACKEND_URL=${BACKEND_URL}|" "${env_file}" || true
    fi
}

start_services() {
    log_info "Starting InferencePack services with engine: ${ENGINE}"

    cd "${SCRIPT_DIR}"

    docker compose --profile "${ENGINE}" up -d

    log_info "Services starting..."
    log_info ""
    log_info "=========================================="
    log_info "  InferencePack is starting up"
    log_info "=========================================="
    log_info "LangFuse UI:     http://localhost:3000"
    log_info "API Endpoint:    http://localhost:8000"
    log_info "Engine:          ${ENGINE}"
    log_info ""
    log_info "To monitor logs: docker compose -f docker-compose.yml --profile ${ENGINE} logs -f"
    log_info "To stop:         docker compose -f docker-compose.yml --profile ${ENGINE} down"
    log_info ""
    log_info "IMPORTANT: If this is your first LangFuse startup:"
    log_info "  1. Visit http://localhost:3000"
    log_info "  2. Sign up with email: netai@smartx.kr"
    log_info "  3. Create a project and generate API keys"
    log_info "  4. Add LANGFUSE_PUBLIC_KEY and LANGFUSE_SECRET_KEY to .env"
    log_info "  5. Restart: docker compose --profile ${ENGINE} restart monitoring-proxy"
    log_info ""
}

wait_for_health() {
    log_info "Waiting for services to be healthy..."
    sleep 5

    local max_attempts=60
    local attempt=0

    while [ $attempt -lt $max_attempts ]; do
        if docker compose ps | grep -q "healthy"; then
            log_info "Services are healthy"
            return 0
        fi
        attempt=$((attempt + 1))
        sleep 5
    done

    log_warn "Some services may still be starting. Check logs with:"
    log_warn "  docker compose --profile ${ENGINE} logs -f"
}

main() {
    log_info "InferencePack Setup Starting..."
    log_info "Script directory: ${SCRIPT_DIR}"

    install_docker
    install_nvidia_container_toolkit
    install_python_deps

    download_models

    select_engine
    setup_backend_url
    setup_env_file
    start_services
    wait_for_health

    log_info "InferencePack setup complete!"
}

main "$@"
